services:
  ocr-model:
    image: vllm/vllm-openai:nightly   # DeepSeek-OCR requires recent vLLM (nightly as of Oct 2025)
    shm_size: '64gb'
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1']       # match your GPU index
              capabilities: [gpu]
    env_file:
      - ../../.env
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
    healthcheck:
      test: [ "CMD", "curl", "-H", "Authorization: Bearer lvm-apikey", "-f", "http://0.0.0.0:6000/v1/models" ]
      interval: 30s
      timeout: 5s
      retries: 20
    ports:
      - "20012:6000"
    volumes:
      - "~/.cache/huggingface:/root/.cache/huggingface"
      # optional: mount a folder for PDFs/images you want to OCR
      - "./data:/data"
    ipc: "host"

    entrypoint: vllm
    command: >
      serve "microsoft/Fara-7B"
      --port 6000
      --max-model-len 131072
      --tensor-parallel-size 2
      --api-key lvm-apikey
      --enable-auto-tool-choice
      --tool-call-parser hermes
