services:
  gemma-hosting:
    image: vllm/vllm-openai:v0.22.1
    container_name: Gemma-4-26B-A4B-it-FP8
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "20012:6000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - "./data:/data"
    ipc: "host"
    shm_size: '64gb'
    command: >
      --model "RedHatAI/gemma-4-26B-A4B-it-FP8-Dynamic"
      --tensor-parallel-size 2
      --max-model-len 131072
      --gpu-memory-utilization 0.90
      --enable-auto-tool-choice
      --reasoning-parser gemma4
      --tool-call-parser gemma4
      --chat-template examples/tool_chat_template_gemma4.jinja
      --limit-mm-per-prompt '{"image": 4}'
      --allowed-local-media-path /data
      --async-scheduling
      --port 6000
      --api-key lvm-apikey
    healthcheck:
      test: [ "CMD", "curl", "-H", "Authorization: Bearer lvm-apikey", "-f", "http://0.0.0.0:6000/v1/models" ]
      interval: 30s
      timeout: 5s
      retries: 20

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
