services:
  chat-model:
    image: vllm/vllm-openai:v0.21.0
    shm_size: '64gb'
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0', '1' ]
              capabilities: [ gpu ]
    env_file:
      - ../../.env
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - CUDA_VISIBLE_DEVICES=0,1
    healthcheck:
      test: [ "CMD", "curl", "-H", "Authorization: Bearer embed-apikey", "-f", "http://0.0.0.0:6000/v1/models" ]
      interval: 30s
      timeout: 5s
      retries: 20
    ports:
      - "60013:6000"
    volumes:
      - "~/.cache/huggingface:/root/.cache/huggingface"
    ipc: "host"

    entrypoint: vllm
    command: serve "BAAI/bge-m3" --dtype auto --port 6000 --tensor-parallel-size 2 --gpu-memory-utilization=0.15 --max-model-len 8192 --max-num-batched-tokens 8192  --max_num_seqs 2 --api-key embed-apikey
